version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build
          command: |
            python3 -m venv test_venv
            . test_venv/bin/activate
            pip install -r requirements.txt
            npm install
            yarn run gulp build-js
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "test_venv"
      - run:
          name: Running tests
          command: |
            . test_venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
