version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node-browsers
    steps:
      - checkout
      - run:
          name: Build
          command: |
            python3 -m venv test_venv
            . test_venv/bin/activate
            pip install -r requirements.txt
            yarn install
            yarn run gulp build-js
      - run:
          name: Tests
          command: |
            . test_venv/bin/activate
            ./manage.py migrate
            ./python3 manage.py test
